import json

nodes = []
edges = []
hyperedges = []

# Helper to add node
def add_node(nid, label, ftype, src):
    nodes.append({'id': nid, 'label': label, 'file_type': ftype, 'source_file': src, 'source_location': None, 'source_url': None, 'captured_at': None, 'author': None, 'contributor': None})

# Code nodes
add_node('perfilcolaboradorservice_perfilcolaboradorservice', 'PerfilColaboradorService', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/PerfilColaboradorService.cs')
add_node('perfilcolaboradorservice_obtenerperfilcolaboradorasync', 'PerfilColaboradorService.ObtenerPerfilColaboradorAsync', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/PerfilColaboradorService.cs')
add_node('perfilcolaboradorservice_actualizarperfilcolaboradorasync', 'PerfilColaboradorService.ActualizarPerfilColaboradorAsync', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/PerfilColaboradorService.cs')
add_node('perfilcolaboradorservice_prepararcliente', 'PerfilColaboradorService.PrepararCliente', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/PerfilColaboradorService.cs')

add_node('maui_solicitudacademicaservice_solicitudacademicaservice', 'SolicitudAcademicaService (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_node('maui_solicitudacademicaservice_crearsolicitudasync', 'SolicitudAcademicaService.CrearSolicitudAsync (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_node('maui_solicitudacademicaservice_obtenersolicitudesdashboardasync', 'SolicitudAcademicaService.ObtenerSolicitudesDashboardAsync (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_node('maui_solicitudacademicaservice_obtenerporidasync', 'SolicitudAcademicaService.ObtenerPorIdAsync (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_node('maui_solicitudacademicaservice_asignarasesorasync', 'SolicitudAcademicaService.AsignarAsesorAsync (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_node('maui_solicitudacademicaservice_postularasolicitudasync', 'SolicitudAcademicaService.PostularASolicitudAsync (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_node('maui_solicitudacademicaservice_seleccionarpostuladoasync', 'SolicitudAcademicaService.SeleccionarPostuladoAsync (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_node('maui_solicitudacademicaservice_obteneravancesasync', 'SolicitudAcademicaService.ObtenerAvancesAsync (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_node('maui_solicitudacademicaservice_subiravanceasync', 'SolicitudAcademicaService.SubirAvanceAsync (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_node('maui_solicitudacademicaservice_agregarcomentarioasync', 'SolicitudAcademicaService.AgregarComentarioAsync (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_node('maui_solicitudacademicaservice_agregararchivoasync', 'SolicitudAcademicaService.AgregarArchivoAsync (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_node('maui_solicitudacademicaservice_aprobaravanceasync', 'SolicitudAcademicaService.AprobarAvanceAsync (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_node('maui_solicitudacademicaservice_rechazaravanceasync', 'SolicitudAcademicaService.RechazarAvanceAsync (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_node('maui_solicitudacademicaservice_prepararcliente', 'SolicitudAcademicaService.PrepararCliente (Maui)', 'code', 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')

add_node('idescargadorarchivos_idescargadorarchivos', 'IDescargadorArchivos', 'code', 'Src/GrupoXpert/GrupoXpert.Shared.UI/Abstracciones/IDescargadorArchivos.cs')
add_node('isolicitudacademicaservice_isolicitudacademicaservice', 'ISolicitudAcademicaService', 'code', 'Src/GrupoXpert/GrupoXpert.Shared.UI/Abstracciones/ISolicitudAcademicaService.cs')

add_node('archivoadjuntodto_archivoadjuntodto', 'ArchivoAdjuntoDto', 'code', 'Src/GrupoXpert/GrupoXpert.Shared.UI/Modelos/Academia/ArchivoAdjuntoDto.cs')
add_node('archivosubidamodelo_archivosubidamodelo', 'ArchivoSubidaModelo', 'code', 'Src/GrupoXpert/GrupoXpert.Shared.UI/Modelos/Academia/ArchivoSubidaModelo.cs')
add_node('avancedto_avancedto', 'AvanceDto', 'code', 'Src/GrupoXpert/GrupoXpert.Shared.UI/Modelos/Academia/AvanceDto.cs')
add_node('comentariodto_comentariodto', 'ComentarioDto', 'code', 'Src/GrupoXpert/GrupoXpert.Shared.UI/Modelos/Academia/ComentarioDto.cs')
add_node('postulaciondto_postulaciondto', 'PostulacionDto', 'code', 'Src/GrupoXpert/GrupoXpert.Shared.UI/Modelos/Academia/PostulacionDto.cs')

add_node('agregarcomentariohandlertests_agregarcomentariohandlertests', 'AgregarComentarioHandlerTests', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AgregarComentarioHandlerTests.cs')
add_node('aprobaravancehandlertests_aprobaravancehandlertests', 'AprobarAvanceHandlerTests', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AprobarAvanceHandlerTests.cs')
add_node('rechazaravancehandlertests_rechazaravancehandlertests', 'RechazarAvanceHandlerTests', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/RechazarAvanceHandlerTests.cs')
add_node('subiravancehandlertests_subiravancehandlertests', 'SubirAvanceHandlerTests', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_node('obteneravancesporsolicitudhandlertests_obteneravancesporsolicitudhandlertests', 'ObtenerAvancesPorSolicitudHandlerTests', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Queries/ObtenerAvancesPorSolicitudHandlerTests.cs')
add_node('avancetests_avancetests', 'AvanceTests', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Domain/Academia/AvanceTests.cs')

add_node('web_program', 'Web Program.cs', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Program.cs')
add_node('web_descargadorarchivos_descargadorarchivos', 'DescargadorArchivos (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/DescargadorArchivos.cs')

add_node('web_solicitudacademicaservice_solicitudacademicaservice', 'SolicitudAcademicaService (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_node('web_solicitudacademicaservice_crearsolicitudasync', 'SolicitudAcademicaService.CrearSolicitudAsync (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_node('web_solicitudacademicaservice_obtenersolicitudesdashboardasync', 'SolicitudAcademicaService.ObtenerSolicitudesDashboardAsync (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_node('web_solicitudacademicaservice_obtenerporidasync', 'SolicitudAcademicaService.ObtenerPorIdAsync (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_node('web_solicitudacademicaservice_asignarasesorasync', 'SolicitudAcademicaService.AsignarAsesorAsync (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_node('web_solicitudacademicaservice_postularasolicitudasync', 'SolicitudAcademicaService.PostularASolicitudAsync (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_node('web_solicitudacademicaservice_seleccionarpostuladoasync', 'SolicitudAcademicaService.SeleccionarPostuladoAsync (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_node('web_solicitudacademicaservice_obteneravancesasync', 'SolicitudAcademicaService.ObtenerAvancesAsync (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_node('web_solicitudacademicaservice_subiravanceasync', 'SolicitudAcademicaService.SubirAvanceAsync (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_node('web_solicitudacademicaservice_agregarcomentarioasync', 'SolicitudAcademicaService.AgregarComentarioAsync (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_node('web_solicitudacademicaservice_agregararchivoasync', 'SolicitudAcademicaService.AgregarArchivoAsync (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_node('web_solicitudacademicaservice_aprobaravanceasync', 'SolicitudAcademicaService.AprobarAvanceAsync (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_node('web_solicitudacademicaservice_rechazaravanceasync', 'SolicitudAcademicaService.RechazarAvanceAsync (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_node('web_solicitudacademicaservice_prepararcliente', 'SolicitudAcademicaService.PrepararCliente (Web)', 'code', 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')

add_node('webapi_program', 'WebApi Program.cs', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Program.cs')

add_node('solicitudesacademicascontroller_solicitudesacademicascontroller', 'SolicitudesAcademicasController', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('solicitudesacademicascontroller_crear', 'SolicitudesAcademicasController.Crear', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('solicitudesacademicascontroller_obtenerdashboard', 'SolicitudesAcademicasController.ObtenerDashboard', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('solicitudesacademicascontroller_obtenerporid', 'SolicitudesAcademicasController.ObtenerPorId', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('solicitudesacademicascontroller_asignarasesor', 'SolicitudesAcademicasController.AsignarAsesor', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('solicitudesacademicascontroller_postular', 'SolicitudesAcademicasController.Postular', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('solicitudesacademicascontroller_seleccionarpostulado', 'SolicitudesAcademicasController.SeleccionarPostulado', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('solicitudesacademicascontroller_obteneravances', 'SolicitudesAcademicasController.ObtenerAvances', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('solicitudesacademicascontroller_subiravance', 'SolicitudesAcademicasController.SubirAvance', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('solicitudesacademicascontroller_agregarcomentario', 'SolicitudesAcademicasController.AgregarComentario', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('solicitudesacademicascontroller_agregararchivo', 'SolicitudesAcademicasController.AgregarArchivo', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('solicitudesacademicascontroller_aprobaravance', 'SolicitudesAcademicasController.AprobarAvance', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('solicitudesacademicascontroller_rechazaravance', 'SolicitudesAcademicasController.RechazarAvance', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')

# Doc nodes
add_node('plan_use_cases_plan', 'Plan Use Cases', 'document', 'docs/plan use-cases/plan.md')
add_node('postular_asignacion_proyecto', 'Postular a Asignacion de Proyecto', 'document', 'docs/use-cases/postular_asignacion_proyecto.md')
add_node('subir_entregable_parcial_avance_fase', 'Subir Entregable Parcial / Avance de Fase', 'document', 'docs/use-cases/subir_entregable_parcial_avance_fase.md')

# Doc concepts
add_node('postular_asignacion_proyecto_postularasolicitudcommand', 'PostularASolicitudCommand', 'rationale', 'docs/use-cases/postular_asignacion_proyecto.md')
add_node('postular_asignacion_proyecto_seleccionarpostuladocommand', 'SeleccionarPostuladoCommand', 'rationale', 'docs/use-cases/postular_asignacion_proyecto.md')
add_node('postular_asignacion_proyecto_solicitudacademica', 'SolicitudAcademica (Domain)', 'rationale', 'docs/use-cases/postular_asignacion_proyecto.md')
add_node('postular_asignacion_proyecto_postulacion', 'Postulacion (Domain)', 'rationale', 'docs/use-cases/postular_asignacion_proyecto.md')

add_node('subir_entregable_parcial_avance_fase_avance', 'Avance (Domain)', 'rationale', 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_node('subir_entregable_parcial_avance_fase_comentario', 'Comentario (Domain)', 'rationale', 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_node('subir_entregable_parcial_avance_fase_archivoadjunto', 'ArchivoAdjunto (Domain)', 'rationale', 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_node('subir_entregable_parcial_avance_fase_subiravancecommand', 'SubirAvanceCommand', 'rationale', 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_node('subir_entregable_parcial_avance_fase_agregarcomentariocommand', 'AgregarComentarioCommand', 'rationale', 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_node('subir_entregable_parcial_avance_fase_agregararchivocommand', 'AgregarArchivoCommand', 'rationale', 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_node('subir_entregable_parcial_avance_fase_aprobaravancecommand', 'AprobarAvanceCommand', 'rationale', 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_node('subir_entregable_parcial_avance_fase_rechazaravancecommand', 'RechazarAvanceCommand', 'rationale', 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_node('subir_entregable_parcial_avance_fase_obteneravancesporsolicitudquery', 'ObtenerAvancesPorSolicitudQuery', 'rationale', 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_node('subir_entregable_parcial_avance_fase_estadoavance', 'EstadoAvance', 'rationale', 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_node('subir_entregable_parcial_avance_fase_tipoavance', 'TipoAvance', 'rationale', 'docs/use-cases/subir_entregable_parcial_avance_fase.md')

# External referenced nodes
add_node('app_agregarcomentariohandler', 'AgregarComentarioHandler', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AgregarComentarioHandlerTests.cs')
add_node('app_aprobaravancehandler', 'AprobarAvanceHandler', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AprobarAvanceHandlerTests.cs')
add_node('app_rechazaravancehandler', 'RechazarAvanceHandler', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/RechazarAvanceHandlerTests.cs')
add_node('app_subiravancehandler', 'SubirAvanceHandler', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_node('app_obteneravancesporsolicitudhandler', 'ObtenerAvancesPorSolicitudHandler', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Queries/ObtenerAvancesPorSolicitudHandlerTests.cs')

add_node('domain_iavancerepository', 'IAvanceRepository', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AgregarComentarioHandlerTests.cs')
add_node('domain_iunidaddetrabajo', 'IUnidadDeTrabajo', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AgregarComentarioHandlerTests.cs')
add_node('domain_avance', 'Avance', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Domain/Academia/AvanceTests.cs')
add_node('domain_solicitudacademica', 'SolicitudAcademica', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_node('domain_isolicitudacademicarepository', 'ISolicitudAcademicaRepository', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_node('domain_iusuariorepository', 'IUsuarioRepository', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_node('domain_iperfilcolaboradorrepository', 'IPerfilColaboradorRepository', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_node('domain_iarchivostorageservice', 'IArchivoStorageService', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_node('domain_usuario', 'Usuario', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_node('domain_perfilcolaborador', 'PerfilColaborador', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_node('domain_tipoavance', 'TipoAvance', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_node('domain_estadoavance', 'EstadoAvance', 'code', 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')

add_node('app_crearsolicitudacademicacommand', 'CrearSolicitudAcademicaCommand', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('app_obtenersolicitudesdashboardquery', 'ObtenerSolicitudesDashboardQuery', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('app_obtenersolicitudporidquery', 'ObtenerSolicitudPorIdQuery', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_node('app_asignarasesorcommand', 'AsignarAsesorCommand', 'code', 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')

# Helper to add edge
def add_edge(src, tgt, rel, conf, score, sfile):
    edges.append({'source': src, 'target': tgt, 'relation': rel, 'confidence': conf, 'confidence_score': score, 'source_file': sfile, 'source_location': None, 'weight': 1.0})

# Implementations
add_edge('maui_solicitudacademicaservice_solicitudacademicaservice', 'isolicitudacademicaservice_isolicitudacademicaservice', 'implements', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_edge('web_solicitudacademicaservice_solicitudacademicaservice', 'isolicitudacademicaservice_isolicitudacademicaservice', 'implements', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_edge('web_descargadorarchivos_descargadorarchivos', 'idescargadorarchivos_idescargadorarchivos', 'implements', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.Web/Services/DescargadorArchivos.cs')

# DI registrations
add_edge('web_program', 'web_solicitudacademicaservice_solicitudacademicaservice', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.Web/Program.cs')
add_edge('web_program', 'web_descargadorarchivos_descargadorarchivos', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.Web/Program.cs')
add_edge('webapi_program', 'solicitudesacademicascontroller_solicitudesacademicascontroller', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.WebApi/Program.cs')

# Maui service -> controller (INFERRED)
add_edge('maui_solicitudacademicaservice_crearsolicitudasync', 'solicitudesacademicascontroller_crear', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_edge('maui_solicitudacademicaservice_obtenersolicitudesdashboardasync', 'solicitudesacademicascontroller_obtenerdashboard', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_edge('maui_solicitudacademicaservice_obtenerporidasync', 'solicitudesacademicascontroller_obtenerporid', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_edge('maui_solicitudacademicaservice_asignarasesorasync', 'solicitudesacademicascontroller_asignarasesor', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_edge('maui_solicitudacademicaservice_postularasolicitudasync', 'solicitudesacademicascontroller_postular', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_edge('maui_solicitudacademicaservice_seleccionarpostuladoasync', 'solicitudesacademicascontroller_seleccionarpostulado', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_edge('maui_solicitudacademicaservice_obteneravancesasync', 'solicitudesacademicascontroller_obteneravances', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_edge('maui_solicitudacademicaservice_subiravanceasync', 'solicitudesacademicascontroller_subiravance', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_edge('maui_solicitudacademicaservice_agregarcomentarioasync', 'solicitudesacademicascontroller_agregarcomentario', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_edge('maui_solicitudacademicaservice_agregararchivoasync', 'solicitudesacademicascontroller_agregararchivo', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_edge('maui_solicitudacademicaservice_aprobaravanceasync', 'solicitudesacademicascontroller_aprobaravance', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')
add_edge('maui_solicitudacademicaservice_rechazaravanceasync', 'solicitudesacademicascontroller_rechazaravance', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')

# Web service -> controller (INFERRED)
add_edge('web_solicitudacademicaservice_crearsolicitudasync', 'solicitudesacademicascontroller_crear', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_edge('web_solicitudacademicaservice_obtenersolicitudesdashboardasync', 'solicitudesacademicascontroller_obtenerdashboard', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_edge('web_solicitudacademicaservice_obtenerporidasync', 'solicitudesacademicascontroller_obtenerporid', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_edge('web_solicitudacademicaservice_asignarasesorasync', 'solicitudesacademicascontroller_asignarasesor', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_edge('web_solicitudacademicaservice_postularasolicitudasync', 'solicitudesacademicascontroller_postular', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_edge('web_solicitudacademicaservice_seleccionarpostuladoasync', 'solicitudesacademicascontroller_seleccionarpostulado', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_edge('web_solicitudacademicaservice_obteneravancesasync', 'solicitudesacademicascontroller_obteneravances', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_edge('web_solicitudacademicaservice_subiravanceasync', 'solicitudesacademicascontroller_subiravance', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_edge('web_solicitudacademicaservice_agregarcomentarioasync', 'solicitudesacademicascontroller_agregarcomentario', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_edge('web_solicitudacademicaservice_agregararchivoasync', 'solicitudesacademicascontroller_agregararchivo', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_edge('web_solicitudacademicaservice_aprobaravanceasync', 'solicitudesacademicascontroller_aprobaravance', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')
add_edge('web_solicitudacademicaservice_rechazaravanceasync', 'solicitudesacademicascontroller_rechazaravance', 'calls', 'INFERRED', 0.85, 'Src/GrupoXpert/GrupoXpert.Web/Services/SolicitudAcademicaService.cs')

# Controller -> Commands/Queries (EXTRACTED)
add_edge('solicitudesacademicascontroller_crear', 'app_crearsolicitudacademicacommand', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_edge('solicitudesacademicascontroller_obtenerdashboard', 'app_obtenersolicitudesdashboardquery', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_edge('solicitudesacademicascontroller_obtenerporid', 'app_obtenersolicitudporidquery', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_edge('solicitudesacademicascontroller_asignarasesor', 'app_asignarasesorcommand', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_edge('solicitudesacademicascontroller_postular', 'postular_asignacion_proyecto_postularasolicitudcommand', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_edge('solicitudesacademicascontroller_seleccionarpostulado', 'postular_asignacion_proyecto_seleccionarpostuladocommand', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_edge('solicitudesacademicascontroller_obteneravances', 'subir_entregable_parcial_avance_fase_obteneravancesporsolicitudquery', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_edge('solicitudesacademicascontroller_subiravance', 'subir_entregable_parcial_avance_fase_subiravancecommand', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_edge('solicitudesacademicascontroller_agregarcomentario', 'subir_entregable_parcial_avance_fase_agregarcomentariocommand', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_edge('solicitudesacademicascontroller_agregararchivo', 'subir_entregable_parcial_avance_fase_agregararchivocommand', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_edge('solicitudesacademicascontroller_aprobaravance', 'subir_entregable_parcial_avance_fase_aprobaravancecommand', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')
add_edge('solicitudesacademicascontroller_rechazaravance', 'subir_entregable_parcial_avance_fase_rechazaravancecommand', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs')

# Tests -> handlers (EXTRACTED)
add_edge('agregarcomentariohandlertests_agregarcomentariohandlertests', 'app_agregarcomentariohandler', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AgregarComentarioHandlerTests.cs')
add_edge('aprobaravancehandlertests_aprobaravancehandlertests', 'app_aprobaravancehandler', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AprobarAvanceHandlerTests.cs')
add_edge('rechazaravancehandlertests_rechazaravancehandlertests', 'app_rechazaravancehandler', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/RechazarAvanceHandlerTests.cs')
add_edge('subiravancehandlertests_subiravancehandlertests', 'app_subiravancehandler', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_edge('obteneravancesporsolicitudhandlertests_obteneravancesporsolicitudhandlertests', 'app_obteneravancesporsolicitudhandler', 'calls', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Queries/ObtenerAvancesPorSolicitudHandlerTests.cs')

# Tests -> repositories (EXTRACTED)
add_edge('agregarcomentariohandlertests_agregarcomentariohandlertests', 'domain_iavancerepository', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AgregarComentarioHandlerTests.cs')
add_edge('agregarcomentariohandlertests_agregarcomentariohandlertests', 'domain_iunidaddetrabajo', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AgregarComentarioHandlerTests.cs')
add_edge('aprobaravancehandlertests_aprobaravancehandlertests', 'domain_iavancerepository', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AprobarAvanceHandlerTests.cs')
add_edge('aprobaravancehandlertests_aprobaravancehandlertests', 'domain_iunidaddetrabajo', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AprobarAvanceHandlerTests.cs')
add_edge('rechazaravancehandlertests_rechazaravancehandlertests', 'domain_iavancerepository', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/RechazarAvanceHandlerTests.cs')
add_edge('rechazaravancehandlertests_rechazaravancehandlertests', 'domain_iunidaddetrabajo', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/RechazarAvanceHandlerTests.cs')
add_edge('subiravancehandlertests_subiravancehandlertests', 'domain_iavancerepository', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_edge('subiravancehandlertests_subiravancehandlertests', 'domain_isolicitudacademicarepository', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_edge('subiravancehandlertests_subiravancehandlertests', 'domain_iperfilcolaboradorrepository', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_edge('subiravancehandlertests_subiravancehandlertests', 'domain_iusuariorepository', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_edge('subiravancehandlertests_subiravancehandlertests', 'domain_iarchivostorageservice', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_edge('subiravancehandlertests_subiravancehandlertests', 'domain_iunidaddetrabajo', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_edge('obteneravancesporsolicitudhandlertests_obteneravancesporsolicitudhandlertests', 'domain_iavancerepository', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Queries/ObtenerAvancesPorSolicitudHandlerTests.cs')
add_edge('obteneravancesporsolicitudhandlertests_obteneravancesporsolicitudhandlertests', 'domain_iperfilcolaboradorrepository', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Queries/ObtenerAvancesPorSolicitudHandlerTests.cs')
add_edge('obteneravancesporsolicitudhandlertests_obteneravancesporsolicitudhandlertests', 'domain_iusuariorepository', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Queries/ObtenerAvancesPorSolicitudHandlerTests.cs')

# Tests -> domain entities (EXTRACTED)
add_edge('avancetests_avancetests', 'domain_avance', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Domain/Academia/AvanceTests.cs')
add_edge('subiravancehandlertests_subiravancehandlertests', 'domain_avance', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_edge('subiravancehandlertests_subiravancehandlertests', 'domain_solicitudacademica', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_edge('subiravancehandlertests_subiravancehandlertests', 'domain_usuario', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_edge('subiravancehandlertests_subiravancehandlertests', 'domain_perfilcolaborador', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_edge('subiravancehandlertests_subiravancehandlertests', 'domain_tipoavance', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_edge('subiravancehandlertests_subiravancehandlertests', 'domain_estadoavance', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/SubirAvanceHandlerTests.cs')
add_edge('agregarcomentariohandlertests_agregarcomentariohandlertests', 'domain_avance', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AgregarComentarioHandlerTests.cs')
add_edge('aprobaravancehandlertests_aprobaravancehandlertests', 'domain_avance', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/AprobarAvanceHandlerTests.cs')
add_edge('rechazaravancehandlertests_rechazaravancehandlertests', 'domain_avance', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Commands/RechazarAvanceHandlerTests.cs')
add_edge('obteneravancesporsolicitudhandlertests_obteneravancesporsolicitudhandlertests', 'domain_avance', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Queries/ObtenerAvancesPorSolicitudHandlerTests.cs')
add_edge('obteneravancesporsolicitudhandlertests_obteneravancesporsolicitudhandlertests', 'domain_tipoavance', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Queries/ObtenerAvancesPorSolicitudHandlerTests.cs')
add_edge('obteneravancesporsolicitudhandlertests_obteneravancesporsolicitudhandlertests', 'domain_estadoavance', 'references', 'EXTRACTED', 1.0, 'Src/GrupoXpert/GrupoXpert.UnitTests/Application/Academia/Queries/ObtenerAvancesPorSolicitudHandlerTests.cs')

# Doc citations (EXTRACTED)
add_edge('postular_asignacion_proyecto', 'solicitudesacademicascontroller_solicitudesacademicascontroller', 'references', 'EXTRACTED', 1.0, 'docs/use-cases/postular_asignacion_proyecto.md')
add_edge('postular_asignacion_proyecto', 'postular_asignacion_proyecto_postularasolicitudcommand', 'cites', 'EXTRACTED', 1.0, 'docs/use-cases/postular_asignacion_proyecto.md')
add_edge('postular_asignacion_proyecto', 'postular_asignacion_proyecto_seleccionarpostuladocommand', 'cites', 'EXTRACTED', 1.0, 'docs/use-cases/postular_asignacion_proyecto.md')
add_edge('postular_asignacion_proyecto', 'postular_asignacion_proyecto_solicitudacademica', 'cites', 'EXTRACTED', 1.0, 'docs/use-cases/postular_asignacion_proyecto.md')
add_edge('postular_asignacion_proyecto', 'postular_asignacion_proyecto_postulacion', 'cites', 'EXTRACTED', 1.0, 'docs/use-cases/postular_asignacion_proyecto.md')

add_edge('subir_entregable_parcial_avance_fase', 'solicitudesacademicascontroller_solicitudesacademicascontroller', 'references', 'EXTRACTED', 1.0, 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_edge('subir_entregable_parcial_avance_fase', 'subir_entregable_parcial_avance_fase_avance', 'cites', 'EXTRACTED', 1.0, 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_edge('subir_entregable_parcial_avance_fase', 'subir_entregable_parcial_avance_fase_subiravancecommand', 'cites', 'EXTRACTED', 1.0, 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_edge('subir_entregable_parcial_avance_fase', 'subir_entregable_parcial_avance_fase_agregarcomentariocommand', 'cites', 'EXTRACTED', 1.0, 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_edge('subir_entregable_parcial_avance_fase', 'subir_entregable_parcial_avance_fase_agregararchivocommand', 'cites', 'EXTRACTED', 1.0, 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_edge('subir_entregable_parcial_avance_fase', 'subir_entregable_parcial_avance_fase_aprobaravancecommand', 'cites', 'EXTRACTED', 1.0, 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_edge('subir_entregable_parcial_avance_fase', 'subir_entregable_parcial_avance_fase_rechazaravancecommand', 'cites', 'EXTRACTED', 1.0, 'docs/use-cases/subir_entregable_parcial_avance_fase.md')
add_edge('subir_entregable_parcial_avance_fase', 'subir_entregable_parcial_avance_fase_obteneravancesporsolicitudquery', 'cites', 'EXTRACTED', 1.0, 'docs/use-cases/subir_entregable_parcial_avance_fase.md')

# Doc-to-doc (EXTRACTED/INFERRED)
add_edge('plan_use_cases_plan', 'postular_asignacion_proyecto', 'references', 'EXTRACTED', 1.0, 'docs/plan use-cases/plan.md')
add_edge('plan_use_cases_plan', 'subir_entregable_parcial_avance_fase', 'references', 'EXTRACTED', 1.0, 'docs/plan use-cases/plan.md')
add_edge('postular_asignacion_proyecto', 'subir_entregable_parcial_avance_fase', 'conceptually_related_to', 'INFERRED', 0.75, 'docs/use-cases/postular_asignacion_proyecto.md')

# Shared data (INFERRED)
add_edge('avancedto_avancedto', 'domain_avance', 'shares_data_with', 'INFERRED', 0.75, 'Src/GrupoXpert/GrupoXpert.Shared.UI/Modelos/Academia/AvanceDto.cs')
add_edge('comentariodto_comentariodto', 'subir_entregable_parcial_avance_fase_comentario', 'shares_data_with', 'INFERRED', 0.75, 'Src/GrupoXpert/GrupoXpert.Shared.UI/Modelos/Academia/ComentarioDto.cs')
add_edge('archivoadjuntodto_archivoadjuntodto', 'subir_entregable_parcial_avance_fase_archivoadjunto', 'shares_data_with', 'INFERRED', 0.75, 'Src/GrupoXpert/GrupoXpert.Shared.UI/Modelos/Academia/ArchivoAdjuntoDto.cs')
add_edge('postulaciondto_postulaciondto', 'postular_asignacion_proyecto_postulacion', 'shares_data_with', 'INFERRED', 0.75, 'Src/GrupoXpert/GrupoXpert.Shared.UI/Modelos/Academia/PostulacionDto.cs')

# Semantic similarity (INFERRED)
add_edge('maui_solicitudacademicaservice_solicitudacademicaservice', 'web_solicitudacademicaservice_solicitudacademicaservice', 'semantically_similar_to', 'INFERRED', 0.95, 'Src/GrupoXpert/GrupoXpert.Maui/Services/SolicitudAcademicaService.cs')

# Hyperedges
hyperedges.append({'id': 'maui_and_web_service_implement_isolicitudacademicaservice', 'label': 'Maui and Web services implement ISolicitudAcademicaService', 'nodes': ['maui_solicitudacademicaservice_solicitudacademicaservice', 'web_solicitudacademicaservice_solicitudacademicaservice', 'isolicitudacademicaservice_isolicitudacademicaservice'], 'relation': 'implement', 'confidence': 'INFERRED', 'confidence_score': 0.95, 'source_file': 'Src/GrupoXpert/GrupoXpert.Shared.UI/Abstracciones/ISolicitudAcademicaService.cs'})
hyperedges.append({'id': 'avance_test_suite', 'label': 'Avance Test Suite', 'nodes': ['avancetests_avancetests', 'subiravancehandlertests_subiravancehandlertests', 'agregarcomentariohandlertests_agregarcomentariohandlertests', 'aprobaravancehandlertests_aprobaravancehandlertests', 'rechazaravancehandlertests_rechazaravancehandlertests', 'obteneravancesporsolicitudhandlertests_obteneravancesporsolicitudhandlertests'], 'relation': 'participate_in', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'docs/use-cases/subir_entregable_parcial_avance_fase.md'})
hyperedges.append({'id': 'academia_dtos', 'label': 'Academia DTOs', 'nodes': ['avancedto_avancedto', 'comentariodto_comentariodto', 'archivoadjuntodto_archivoadjuntodto', 'archivosubidamodelo_archivosubidamodelo', 'postulaciondto_postulaciondto'], 'relation': 'form', 'confidence': 'INFERRED', 'confidence_score': 0.75, 'source_file': 'Src/GrupoXpert/GrupoXpert.Shared.UI/Modelos/Academia'})
hyperedges.append({'id': 'solicitudesacademicascontroller_avance_endpoints', 'label': 'SolicitudesAcademicasController Avance Endpoints', 'nodes': ['solicitudesacademicascontroller_obteneravances', 'solicitudesacademicascontroller_subiravance', 'solicitudesacademicascontroller_agregarcomentario', 'solicitudesacademicascontroller_agregararchivo', 'solicitudesacademicascontroller_aprobaravance', 'solicitudesacademicascontroller_rechazaravance'], 'relation': 'participate_in', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'Src/GrupoXpert/GrupoXpert.WebApi/Controllers/SolicitudesAcademicasController.cs'})
hyperedges.append({'id': 'postulacion_flow_commands', 'label': 'Postulacion Flow Commands', 'nodes': ['postular_asignacion_proyecto_postularasolicitudcommand', 'postular_asignacion_proyecto_seleccionarpostuladocommand', 'postular_asignacion_proyecto_solicitudacademica', 'postular_asignacion_proyecto_postulacion'], 'relation': 'participate_in', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'docs/use-cases/postular_asignacion_proyecto.md'})
hyperedges.append({'id': 'avance_lifecycle_commands', 'label': 'Avance Lifecycle Commands', 'nodes': ['subir_entregable_parcial_avance_fase_subiravancecommand', 'subir_entregable_parcial_avance_fase_agregarcomentariocommand', 'subir_entregable_parcial_avance_fase_agregararchivocommand', 'subir_entregable_parcial_avance_fase_aprobaravancecommand', 'subir_entregable_parcial_avance_fase_rechazaravancecommand', 'subir_entregable_parcial_avance_fase_avance'], 'relation': 'participate_in', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'docs/use-cases/subir_entregable_parcial_avance_fase.md'})

result = {'nodes': nodes, 'edges': edges, 'hyperedges': hyperedges, 'input_tokens': 0, 'output_tokens': 0}

with open(r'E:\Documentos\Proyectos\GrupoXpert\graphify-out\.graphify_chunk_03.json', 'w', encoding='utf-8') as f:
    json.dump(result, f, ensure_ascii=False, indent=2)
print('done')
