<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\CotizacionPago.cs" />
    <Compile Remove="Models\Servicio.cs" />
    <Compile Remove="Models\SolicitudAcademica.cs" />
    <Compile Remove="Models\Usuario.cs" />
  </ItemGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="8.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GrupoXpert.Core\GrupoXpert.Core.csproj" />
    <ProjectReference Include="..\GrupoXpert.Tools\GrupoXpert.Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Components\Dashboard2.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

</Project>
